server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: cars-public
          uri: http://msvc-cars:9191
          predicates:
            - Path=/model/**,/trans/**,/fuel/**,/type/**,/car/**,/brand/**,/version/**
            - Method=GET
          filters:
            - AddRequestHeader=X-GATEWAY-SECRET, key-microservices

        - id: cars-secure
          uri: http://msvc-cars:9191
          predicates:
            - Path=/model/**,/trans/**,/fuel/**,/type/**,/car/**,/brand/**,/version/**
            - Method=POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - TokenRelay
            - AddRequestHeader=X-GATEWAY-SECRET, key-microservices

        - id: security-login-register
          uri: http://msvc-security:8181
          predicates:
            - Path=/keycloak/user/**
            - Method=POST
          filters:
            - AddRequestHeader=X-GATEWAY-SECRET, key-microservices

        - id: security
          uri: http://msvc-security:8181
          predicates:
            - Path=/keycloak/user/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - TokenRelay
            - AddRequestHeader=X-GATEWAY-SECRET, key-microservices

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/cars-realm-dev
jwt:
  auth:
    converter:
      principalAttribute: preferred_username
      resource-id: cars-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka